language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem update --remote bundler
script:
  - bundle exec rspec
  - bundle exec ridecharge-rubocop -R -d
